default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: crewtunes/development

test:
  <<: *default
  database: crewtunes/test

production:
  <<: *default
  database: crewtunes/production
